par(mfrow=c(2,2))
with(energy_df,{plot(Date, Global_active_power,ylab="Global Active Power",type="l")
				plot(Date,Voltage,xlab="datetime",type="l")
				plot(Date, Sub_metering_1, col = "black", type = "l", ylab="Energy Sub Metering")
				lines(Date, Sub_metering_2, col = "red")
				lines(Date, Sub_metering_3, col = "blue")
				plot(Date,Global_reactive_power,xlab="datetime",type="l")})
dev.copy(png, file="plot4.png")
dev.off()